---
- hosts: all
  become: yes
  tasks:
    - name: Download required roles
      delegate_to: localhost
      command: ansible-galaxy install -r {{ playbook_dir }}/requirements.yml
      become: no
      changed_when: False
      tags: always
    - block:
      - include_role: name=baztian.apt_upgrade
      tags: apt_upgrade
    - block:
      - include_role: name=baztian.git
      tags: git
    - block:
      - include_role: name=baztian.python
      tags: python
    - block:
      - include_role: name=baztian.asdf
      tags: asdf
    - block:
      - include_role: name=baztian.keepass
      tags: keepass
    - block:
      - include_role: name=baztian.docker
      tags: docker
    - block:
      - include_role: name=baztian.java
      tags: java
    - block:
      - include_role: name=baztian.vscode
      tags: vscode
    - block:
      - include_role: name=baztian.jetbrains_toolbox
      tags: jetbrains_toolbox
    - block:
      - include_role: name=baztian.js
      tags: js
    - block:
      - include_role: name=baztian.dev_tools
      tags: dev_tools
    - block:
      - include_role: name=baztian.aws
      tags: aws
    - block:
      - include_role: name=baztian.other_installs
      tags: other_installs
    - block:
      - include_role: name=baztian.buildnotify
      tags: buildnotify
    - block:
      - include_role: name=baztian.mob
      tags: mob
    - block:
      - include_role: name=baztian.adr_tools
      tags: adr_tools
