- src: baztian.apt_upgrade
- src: baztian.git
- src: baztian.asdf
- src: baztian.docker
- src: baztian.vscode
- src: baztian.python
- src: baztian.pip_venv
- src: baztian.adr_tools
- src: baztian.dev_tools
- src: baztian.java
- src: baztian.aws
- src: baztian.keepass
- src: baztian.jetbrains_toolbox
- src: baztian.js
- src: baztian.other_installs
- src: baztian.buildnotify
- src: baztian.mob
- src: baztian.adr_tools
